"""initial tables

Revision ID: 8bac7f33a20a
Revises: 53e19b790ebd
Create Date: 2026-07-21 00:09:52.204516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bac7f33a20a'
down_revision: Union[str, None] = '53e19b790ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
